
experiment_name:
  snn_conv_1_gesture_avg

pytorch_seed:
  2

hyperparameters:
  # default parameters
  length:
    30
  batch_size:
    64
  synapse_type:
    'dual_exp'
  epoch:
    100
  droupout:
    0.3
  tau_m:
    4
  tau_s:
    1
  filter_tau_m:
    4
  filter_tau_s:
    1
  train_coefficients:
    True
  train_bias:
    True
  membrane_filer:
    False

optimizer:
  optimizer_choice:
    'Adam'
  Adam:
    lr: 0.0001
  AdamW:
    lr: 0.0001
  SGD:
    lr: 0.0001

scheduler:
  scheduler_choice:
    'MultiStepLR'
  MultiStepLR:
    milestones:
      - 50
      - 100
    gamma:
      0.1
  CosineAnnealingWarmRestarts:
    T_0:
      1000
  CyclicLR:
    base_lr:
      0.0001
    max_lr:
      0.001
    step_size_up:
      2000

# configs for saving checkpoint
save_checkpoint:
  True
checkpoint_base_name:
  checkpoint_
checkpoint_base_path:
  ./checkpoint/

# the checkpoint used for test
test_checkpoint_path:
  ./checkpoint/checkpoint_snn_conv_1_gesture_avg_0_20210125-105229
  # ./checkpoint/pretrained_snn_conv_1_gesture_avg

acc_file_name:
  'snn_conv_1_gesture_avg_acc.csv'

